fix(server): aws lambda
good-idea/sane-shopify pull request #159
Opened 2021-03-30 16:39 UTC by liqueflies

Fix for aws lambda.

The problem was basically two:

1. Move from native `fetch` to `cross-fetch` (no, isomorphic was not working :/)
2. When you use webhook in async/await format you must return an object with `statusCode` and `body`

🎉 

Happy merge, hope you like it 👯  🧦

2021-03-30 16:43 UTC, good-idea requested changes

2021-03-30 16:43 UTC, good-idea commented on packages/server/src/aws/index.ts
> +} from '@six-socks-studio/sane-shopify-types'
Once this is changed back to `@sane-shopify` it should be good to go! Does `@sane-shopify/types` need to be updated or was this just something you did to get your local version running?

2021-03-30 16:43 UTC, good-idea commented
Thank you!!

2021-03-30 16:44 UTC, good-idea commented
A second note.. I would expect these errors to throw with the stack trace pointing to the source typescript files, not the compiled JS... is this an AWS-specific thing? (I haven't used lambdas in a while)

2021-03-30 16:45 UTC, good-idea approved these changes

2021-03-30 16:45 UTC, liqueflies commented
UPDATED: sorry for wrong package reference.

no changes on types.

2021-03-30 16:46 UTC, liqueflies commented
> A second note.. I would expect these errors to throw with the stack trace pointing to the source typescript files, not the compiled JS... is this an AWS-specific thing? (I haven't used lambdas in a while)

I didn't get what you would expect for that...

2021-03-30 16:52 UTC, good-idea commented
I'd expect the stack trace to look like this:

```
4:53:12 PM: 2020-11-10T15:53:12.187Z	4b7f18b7-99da-4b6a-87e9-1b2edc4a0451	INFO	TypeError: realFetch.call is not a function
    at module.exports (/var/task/src/lambda/onProductUpdate.ts:15:19) <- .ts, not .js
```

But, this was a fetch-related thing that is resolved anyway! I just want to add some info to the docs about this

2021-03-30 16:54 UTC, good-idea commented
Oops those failed builds are my fault. I'll fix and merge

2021-03-31 07:57 UTC, liqueflies commented
> I'd expect the stack trace to look like this:
> 
> ```
> 4:53:12 PM: 2020-11-10T15:53:12.187Z	4b7f18b7-99da-4b6a-87e9-1b2edc4a0451	INFO	TypeError: realFetch.call is not a function
>     at module.exports (/var/task/src/lambda/onProductUpdate.ts:15:19) <- .ts, not .js
> ```
> 
> But, this was a fetch-related thing that is resolved anyway! I just want to add some info to the docs about this

Ok got what you are asking me. I think this is how lambda is bundled. It depends on how you build your lambda, is not something "node nuxt/next server integrated" but is bundled on it's own and minifies code. Maybe it's just webpack configuration stuff.

2021-04-02 01:59 UTC, good-idea commented
I created a new PR to merge this in since it wouldn't let me update yours. Thanks for your work on this!

2021-04-02 01:59 UTC, closed without merging